name: Merge Test Branch with Main

on:
  push:
    branches: [ test ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Merge test branch
        run: git merge test

      - name: Push changes to main branch
        uses: ad-m/github-push-action@master
        with:
          branch: main