name: Work 1 Dorx
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Something
      run: echo "Hola Pitaya!"
    - name: Print Something 2
      run: echo "Esto es otra impresión"